version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: email-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: email_signals
      MYSQL_USER: es_user
      MYSQL_PASSWORD: Atharv_test
      MYSQL_ROOT_PASSWORD: Atharv_test
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: .
    container_name: email-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: email_signals
      DB_USER: es_user
      DB_PASS: Atharv_test
      API_KEY: SuperSecretApiKey123
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  db_data:
